version: "3.9"

services:
  fastapi:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "1233:1233"
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - DSN=postgresql://postgres:postgres@db:5432/reviews_db  


  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reviews_db"]
      interval: 5s
      timeout: 5s
      retries: 15

volumes:
  pgdata: