services:
  pgdb:
    image: postgres:16
    container_name: postgres_reviews
    restart: unless-stopped
    environment:
      POSTGRES_DB: reviews_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:15432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
#      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 60s
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.localdomain
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_DISABLE_POSTFIX: 1
    ports:
      - 127.0.0.1:5445:80
    depends_on:
      pgdb:
        condition: service_healthy